### ISSUE TITLE
dependencies requirements

### ISSUE THREAD

**Issue by rvalieris** [dunovank/jupyterlab_legos_ui#2]
hello, thanks for the nice themes !

I had trouble installing it because it requires some very specific versions of other packages:

https://github.com/dunovank/jupyterlab_legos_ui/blob/4998d01a969758cef5cd37d197c0bd8215090276/setup.py#L73-L77

more specifically nbconvert and jedi, are these specific versions really necessary ?

**Comment by dunovank** [comment]
This was resolved a few months back, forgot to close it. Thanks for the contribution!
